language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - sudo apt-get install libpq-dev python-dev
  - sudo apt-get install python3-psycopg2
install:
  - pip install -r backend/requirements.txt
# command to run tests
script:
  - pytest
